Ultimately, my goal here is to pull data from the file that will make sense to report on.

In [50]:
import plotly.express as px
import plotly as pl
import plotly.io as pio
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [51]:
npa = pd.read_csv('Nutrition__Physical_Activity__and_Obesity.csv')
npa.head()

C:\Users\djanke2\AppData\Local\Temp\ipykernel_16628\191502378.py:1: DtypeWarning:

Columns (0: Data_Value_Unit, 1: Total) have mixed types. Specify dtype option on import or set low_memory=False.

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$15,000 - $24,999",INC,INC1525
1,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$25,000 - $34,999",INC,INC2535
2,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$35,000 - $49,999",INC,INC3550
3,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$50,000 - $74,999",INC,INC5075
4,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$75,000 or greater",INC,INC75PLUS

In [52]:
#Look for obesity info
npa = npa[npa["Topic"].str.contains("Obesity", case=False, na=False)]

#Get the correct value types
npa["Data_Value"] = pd.to_numeric(npa["Data_Value"], errors="coerce")

#plot information for specific info
plot_npa = npa.dropna(subset=["Age_yrs", "Data_Value", "LocationDesc"])

In [53]:
npa.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$15,000 - $24,999",INC,INC1525
1,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$25,000 - $34,999",INC,INC2535
2,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$35,000 - $49,999",INC,INC3550
3,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$50,000 - $74,999",INC,INC5075
4,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$75,000 or greater",INC,INC75PLUS

In [54]:
plot_npa = (
    plot_npa
    .groupby(["LocationDesc", "Age_yrs"])["Data_Value"]
    .mean()
    .reset_index()
)

In [55]:
import plotly.graph_objects as go

states = plot_npa["LocationDesc"].unique()

fig = go.Figure()

# Add one trace per state
for state in states:
    state_npa = plot_npa[plot_npa["LocationDesc"] == state]
    
    fig.add_trace(
        go.Scatter(
            x=state_npa["Age_yrs"],
            y=state_npa["Data_Value"],
            mode="lines+markers",
            name=state,
            visible=(state == states[0]))
    )
fig.show()

In [56]:
import plotly.graph_objects as go

states = plot_npa["LocationDesc"].unique()

fig1 = go.Figure()

# Add one trace per state
for state in states:
    state_npa = plot_npa[plot_npa["LocationDesc"] == state]
    
    fig1.add_trace(
        go.Scatter(
            x=state_npa["Age_yrs"],
            y=state_npa["Data_Value"],
            mode="lines+markers",
            name=state,
            visible=(state == states[0])
            )
    )

# Create dropdown buttons
buttons = []

for i, state in enumerate(states):
    visibility = [False] * len(states)
    visibility[i] = True
    
    buttons.append(
        dict(
            label=state,
            method="update",
            args=[
                {"visible": visibility},
                {"title": f"Obesity Rates by Age in {state}"}
            ]
        )
    )
# Add dropdown to layout
fig1.update_layout(
    title=f"Obesity Rates by Age in {states[0]}",
    xaxis_title="Age Group",
    yaxis_title="Obesity Rate (%)",
    updatemenus=[
        dict(
            active=0,
            buttons=buttons,
            x=1.15,
            y=1
        )
    ]
)

fig1.show()

In [57]:
import plotly.graph_objects as go

states = plot_npa["LocationDesc"].unique()

fig2 = go.Figure()

# Add one trace per state
for state in states:
    state_npa = plot_npa[plot_npa["LocationDesc"] == state]
    
    fig2.add_trace(
        go.Scatter(
            x=state_npa["Age_yrs"],
            y=state_npa["Data_Value"],
            mode="lines+markers",
            name=state,
            visible=(state == states[0])  
        )
    )

# Create dropdown buttons
buttons = []

for i, state in enumerate(states):
    visibility = [False] * len(states)
    visibility[i] = True
    
    buttons.append(
        dict(
            label=state,
            method="update",
            args=[
                {"visible": visibility},
                {"title": f"Obesity Rates by Age in {state}"}
            ]
        )
    )
# Add dropdown to layout
fig2.update_layout(
    title=f"Obesity Rates by Age in {states[0]}",
    xaxis_title="Age Group",
    yaxis_title="Obesity Rate (%)",
    updatemenus=[
        dict(
            active=0,
            buttons=buttons,
            x=1.15,
            y=1
        )
    ]
)

fig2 = px.line(
    plot_npa,
    x="Age_yrs",
    y="Data_Value",
    color="LocationDesc",
    title="Obesity Rates by Age Across States"
)

fig2.show()

In [58]:
#Keep only obesity-related rows
npa = npa[npa["Topic"].str.contains("Obesity", case=False, na=False)]

#Convert numeric
npa["Data_Value"] = pd.to_numeric(npa["Data_Value"], errors="coerce")

#Keep needed columns
plot_npa = npa.dropna(subset=["Sex", "LocationDesc", "Data_Value"])

#filter to a single year for clarity
#plot_npa = plot_npa[plot_npa["YearStart"] == 2021]

#Average obesity rate per state + sex/gender
plot_npa = (
    plot_npa
    .groupby(["LocationDesc", "Sex"])["Data_Value"]
    .mean()
    .reset_index()
)

In [62]:
import plotly.graph_objects as go

states = plot_npa["LocationDesc"].unique()

fig3 = go.Figure()

# Add traces (one per state)
for state in states:
    state_npa = plot_npa[plot_npa["LocationDesc"] == state]
    
    fig3.add_trace(
        go.Bar(
            x=state_npa["Sex"],
            y=state_npa["Data_Value"],
            name=state,
            visible=(state == states[0])
    ))

# Dropdown buttons
buttons = []

for i, state in enumerate(states):
    visibility = [False] * len(states)
    visibility[i] = True
    
    buttons.append(
        dict(
            label=state,
            method="update",
            args=[
                {"visible": visibility},
                {"title": f"Obesity Rates by Sex in {state}"}
            ]
        )
    )

# Layout
fig3.update_layout(
    title=f"Obesity Rates by Sex in {states[0]}",
    xaxis_title="Sex",
    yaxis_title="Obesity Rate (%)",
    updatemenus=[
        dict(
            buttons=buttons,
            direction="down",
            x=1.15,
            y=1
        )
    ])


fig3.show()

In [ ]:
import plotly.express as px

#Filter to a state
state = plot_npa["LocationDesc"].unique()[0]

fig4 = px.bar(
    plot_npa[plot_npa["LocationDesc"] == state],
    x="Sex",
    y="Data_Value",
    color="Sex",
    title=f"Obesity Rates by Sex in {state}"
)

fig4.show()

In [63]:
#Convert to numeric
npa["Data_Value"] = pd.to_numeric(npa["Data_Value"], errors="coerce")

# Clean data
plot_npa = npa.dropna(subset=["Sex", "LocationDesc", "Data_Value"])

#Filter to one year
#plot_npa = plot_npa[plot_df["Year"] == 2021]

#Combine data
plot_npa= (
    plot_npa
    .groupby(["LocationDesc", "Sex"])["Data_Value"]
    .mean()
    .reset_index()
)

In [64]:
import plotly.express as px

fig5 = px.bar(
    plot_npa,
    x="Sex",
    y="Data_Value",
    color="Sex",
    animation_frame="LocationDesc",  # this creates the state selector
    title="Obesity Rates by Sex by State"
)
fig5.update_layout(
    xaxis_title="Sex",
    yaxis_title="Obesity Rate (%)"
)

fig5.show()

In [65]:
import pandas as pd

#keep obesity data
npa = npa[npa["Topic"].str.contains("Obesity", case=False, na=False)]

#pull rows where question relates to physical activity time
npa_pa = npa[npa["Question"].str.contains("physical activity|minutes", case=False, na=False)]

#convert to numeric
npa_pa["Data_Value"] = pd.to_numeric(npa_pa["Data_Value"], errors="coerce")

#clean data
plot_npa = npa_pa.dropna(subset=["Question", "LocationDesc", "Data_Value"])

#filter to one state OR keep all
#state = "Ohio"
#plot_npa = plot_npa[plot_npa["LocationDesc"] == state]

#filter to one year
#plot_npa = plot_npa[plot_npa["Year"] == 2021]

#combine data
plot_npa = (
    plot_npa
    .groupby(["Question"])["Data_Value"]
    .mean()
    .reset_index()
)

In [66]:
import plotly.express as px

fig6 = px.line(
    plot_npa,
    x="Question",
    y="Data_Value",
    markers=True,
    title=f"Obesity Rates by Physical Activity Amount ({state})"
)

fig6.update_layout(
    xaxis_title="Physical Activity Level (from Question)",
    yaxis_title="Obesity Rate (%)"
)
fig6.show()

In [67]:
plot_npa = (
    npa_pa
    .groupby(["LocationDesc", "Question"])["Data_Value"]
    .mean()
    .reset_index()
)

fig7 = px.bar(
    plot_npa,
    x="LocationDesc",
    y="Data_Value",
    animation_frame="Question",  # toggle activity level
    title="Obesity Rates by State Across Physical Activity Levels"
)
fig7.show()

I'm not sure why these didn't pull data. I'm guessing there isn't data in the areas it went to in the dataset.