My initial plan was to take my dataset and see the best way to pull data that was provided. That way I could analyze it and see what variables could be made that made sense in presenting the information in a way that it would tell a story. Below you'll see some of the simple ways I tried to present the data, but found I was having issues with my chosen dataset and the way it actually complied the information.

In [3]:
import plotly.express as px
import plotly as pl
import plotly.io as pio
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [ ]:
#File renamed to Weight.csv and retrieved from https://catalog.data.gov/dataset/normal-weight-overweight-and-obesity-among-adults-aged-20-and-over-by-selected-characteris-8e2b1
wt = pd.read_csv('weight.csv')
wt.head()

,INDICATOR,PANEL,PANEL_NUM,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE,SE,FLAG
0,"Normal weight, overweight, and obesity among a...",Normal weight (BMI from 18.5 to 24.9),1,"Percent of population, age-adjusted",1,Total,1,20 years and over,1.1,1988-1994,1,20 years and over,1.0,41.6,0.8,NaN
1,"Normal weight, overweight, and obesity among a...",Normal weight (BMI from 18.5 to 24.9),1,"Percent of population, age-adjusted",1,Total,1,20 years and over,1.1,1999-2002,2,20 years and over,1.0,33.0,0.8,NaN
2,"Normal weight, overweight, and obesity among a...",Normal weight (BMI from 18.5 to 24.9),1,"Percent of population, age-adjusted",1,Total,1,20 years and over,1.1,2001-2004,3,20 years and over,1.0,32.3,0.7,NaN
3,"Normal weight, overweight, and obesity among a...",Normal weight (BMI from 18.5 to 24.9),1,"Percent of population, age-adjusted",1,Total,1,20 years and over,1.1,2003-2006,4,20 years and over,1.0,31.6,0.8,NaN
4,"Normal weight, overweight, and obesity among a...",Normal weight (BMI from 18.5 to 24.9),1,"Percent of population, age-adjusted",1,Total,1,20 years and over,1.1,2005-2008,5,20 years and over,1.0,30.8,0.7,NaN

In [5]:
wt['Weight_Category'] = wt['STUB_LABEL']
wt['Group']=wt['STUB_NAME']
wt.head()

,INDICATOR,PANEL,PANEL_NUM,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE,SE,FLAG,Weight_Category,Group
0,"Normal weight, overweight, and obesity among a...",Normal weight (BMI from 18.5 to 24.9),1,"Percent of population, age-adjusted",1,Total,1,20 years and over,1.1,1988-1994,1,20 years and over,1.0,41.6,0.8,NaN,20 years and over,Total
1,"Normal weight, overweight, and obesity among a...",Normal weight (BMI from 18.5 to 24.9),1,"Percent of population, age-adjusted",1,Total,1,20 years and over,1.1,1999-2002,2,20 years and over,1.0,33.0,0.8,NaN,20 years and over,Total
2,"Normal weight, overweight, and obesity among a...",Normal weight (BMI from 18.5 to 24.9),1,"Percent of population, age-adjusted",1,Total,1,20 years and over,1.1,2001-2004,3,20 years and over,1.0,32.3,0.7,NaN,20 years and over,Total
3,"Normal weight, overweight, and obesity among a...",Normal weight (BMI from 18.5 to 24.9),1,"Percent of population, age-adjusted",1,Total,1,20 years and over,1.1,2003-2006,4,20 years and over,1.0,31.6,0.8,NaN,20 years and over,Total
4,"Normal weight, overweight, and obesity among a...",Normal weight (BMI from 18.5 to 24.9),1,"Percent of population, age-adjusted",1,Total,1,20 years and over,1.1,2005-2008,5,20 years and over,1.0,30.8,0.7,NaN,20 years and over,Total

In [6]:
print(wt.columns)

Index(['INDICATOR', 'PANEL', 'PANEL_NUM', 'UNIT', 'UNIT_NUM', 'STUB_NAME',
       'STUB_NAME_NUM', 'STUB_LABEL', 'STUB_LABEL_NUM', 'YEAR', 'YEAR_NUM',
       'AGE', 'AGE_NUM', 'ESTIMATE', 'SE', 'FLAG', 'Weight_Category', 'Group'],
      dtype='str')

In [49]:
#Create a line graph
line_wt = wt[wt['Group'] == 'Total']
fig1 = px.line(
    line_wt,
    x='YEAR',
    y='ESTIMATE',
    color='Weight_Category',
    title='Trends in Weight Categories Over Time (U.S. Adults)',
    markers=True)
fig1.update_layout(
    xaxis_title='Year',
    yaxis_title='Percentage (%)')
fig1.show()

In [ ]:
#Get most recent year by using a filter
latest_year = wt['YEAR'].max()
bar_wt = wt[
    (wt['YEAR'] == latest_year) &
    (wt['Weight_Category'] == 'Obesity') &
    (wt['Group'] == 'Sex')]
fig2 = px.bar(
    bar_wt,
    x='STUB_LABEL',
    y='ESTIMATE',
    color='STUB_LABEL',
    title=f'Obesity Rates by Sex ({latest_year})',
    text='ESTIMATE')
fig2.update_layout(
    xaxis_title='Sex',
    yaxis_title='Obesity Rate (%)',
    showlegend=False)
fig2.show()
#I have no idea why data did not populate below.

In [ ]:
stack_wt = wt[
    (wt['YEAR'] == latest_year) &
    (wt['Group'] == 'Sex')]
fig3 = px.bar(
    stack_wt,
    x='STUB_LABEL',
    y='ESTIMATE',
    color='Weight_Category',
    title=f'Weight Category Distribution by Sex ({latest_year})')
fig3.update_layout(
    barmode='stack',
    xaxis_title='Sex',
    yaxis_title='Percentage (%)')
fig3.show()
#Not what I was going for and will need to research a better way to portray

In [ ]:
#Line Graph comparison of male vs female over time.
facet_wt = wt[wt['Group'] == 'Sex']
fig4 = px.line(
    facet_wt,
    x='YEAR',
    y='ESTIMATE',
    color='Weight_Category',
    facet_col='STUB_LABEL',
    title='Weight Trends by Sex Over Time',
    markers=True)
fig4.update_layout(
    xaxis_title='Year',
    yaxis_title='Percentage (%)')
fig4.show()
#Needs cleaned up - happy with the markers

In [ ]:
#Demographic group data
fig5 = px.line(
    wt,
    x='YEAR',
    y='ESTIMATE',
    color="Weight_Category",
    animation_frame='Group',
    title='Interactive Trends by Demographic Group',
    markers=True)
fig5.show()
#There has to be a better way to portray

In [52]:

#Scatter plot of obesity rates over time
fig6 = px.scatter(
    wt,
    x="YEAR",
    y="ESTIMATE",
    title="Scatterplot of Obesity Rates Over Time")
fig6.show()

In [54]:
#Obesity rates by gender scatterplot
gender_wt = wt[wt["STUB_NAME"].str.contains("Sex", case=False, na=False)]
fig7 = px.scatter(
    gender_wt,
    x="YEAR",
    y="ESTIMATE",
    color="STUB_LABEL",
    title="Obesity Rates by Gender (Scatterplot)")
fig7.show()

In [55]:
#Scatterplot of obesity rates by race/ethnicity
race_wt = wt[wt["STUB_NAME"].str.contains("Race", case=False, na=False)]
fig8 = px.scatter(
    race_wt,
    x="YEAR",
    y="ESTIMATE",
    color="STUB_LABEL",
    title="Obesity Rates by Race/Ethnicity (Scatterplot)")
fig8.show()

In [ ]:
#Obesity rates by age Scatterplot
age_wt = wt[wt["STUB_NAME"].str.contains("Age", case=False, na=False)]
fig9 = px.scatter(
    age_wt,
    x="YEAR",
    y="ESTIMATE",
    color="AGE",
    title="Obesity Rates by Age Group (Scatterplot)")
fig9.show()

In [ ]:
#Obesity rates scatterplot with trendline
fig10 = px.scatter(
    wt,
    x="YEAR",
    y="ESTIMATE",
    trendline="ols",
    title="Obesity Rates Over Time with Trendline")
fig10.show()
#Completely lost on why this didn't work

ValueError: Could not convert value of 'x' ('YEAR') into a numeric type. If 'x' contains stringified dates, please convert to a datetime column.

In [ ]:
#Obesity rates bubble scatterplot
fig11 = px.scatter(
    wt,
    x="YEAR",
    y="ESTIMATE",
    color="STUB_NAME",
    size="ESTIMATE",
    hover_data=["STUB_LABEL"],
    title="Bubble Scatterplot of Obesity Rates")
fig11.show()
#Completely lost on why this didn't work

ValueError:
    Invalid element(s) received for the 'size' property of scattergl.marker
        Invalid elements include: [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

    The 'size' property is a number and may be specified as:
      - An int or float in the interval [0, inf]
      - A tuple, list, or one-dimensional numpy array of the above

The Weight Dataset has been challenging to work with and I'm completely frustrated. Is the dataset aggregated and causing issues? I found another option that might make more sense for my project and started over below with possible graphs/charts. Overall, I would need to change the question I'm trying to answer to something similar but that makes more sense with data in this .csv file.

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
#New Dataset retrieved from https://catalog.data.gov/dataset/nutrition-physical-activity-and-obesity-behavioral-risk-factor-surveillance-system
npa = pd.read_csv('Nutrition__Physical_Activity__and_Obesity.csv')
npa.head()

C:\Users\djanke2\AppData\Local\Temp\ipykernel_8912\191502378.py:1: DtypeWarning:

Columns (0: Data_Value_Unit, 1: Total) have mixed types. Specify dtype option on import or set low_memory=False.

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$15,000 - $24,999",INC,INC1525
1,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$25,000 - $34,999",INC,INC2535
2,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$35,000 - $49,999",INC,INC3550
3,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$50,000 - $74,999",INC,INC5075
4,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$75,000 or greater",INC,INC75PLUS

In [23]:
print(npa.columns)

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource',
       'Class', 'Topic', 'Question', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit ',
       'Sample_Size', 'Total', 'Age(years)', 'Education', 'Sex', 'Income',
       'Race/Ethnicity', 'GeoLocation', 'ClassID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'LocationID', 'StratificationCategory1',
       'Stratification1', 'StratificationCategoryId1', 'StratificationID1'],
      dtype='str')

In [ ]:
#Make columns numeric for ease of use later
npa["Data_Value"] = pd.to_numeric(npa["Data_Value"], errors="coerce")
npa["Low_Confidence_Limit"] = pd.to_numeric(npa["Low_Confidence_Limit"], errors="coerce")
npa["High_Confidence_Limit "] = pd.to_numeric(npa["High_Confidence_Limit "], errors="coerce")
npa["Sample_Size"] = pd.to_numeric(npa["Sample_Size"], errors="coerce")

In [26]:
npa.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$15,000 - $24,999",INC,INC1525
1,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$25,000 - $34,999",INC,INC2535
2,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$35,000 - $49,999",INC,INC3550
3,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$50,000 - $74,999",INC,INC5075
4,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$75,000 or greater",INC,INC75PLUS

In [ ]:
#Make an overall Year column for later
npa["Year"] = npa["YearStart"]

In [28]:
npa.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1,Year
0,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS,OWS1,Q036,VALUE,1,Income,"$15,000 - $24,999",INC,INC1525,2016
1,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS,OWS1,Q036,VALUE,1,Income,"$25,000 - $34,999",INC,INC2535,2016
2,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS,OWS1,Q036,VALUE,1,Income,"$35,000 - $49,999",INC,INC3550,2016
3,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS,OWS1,Q036,VALUE,1,Income,"$50,000 - $74,999",INC,INC5075,2016
4,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS,OWS1,Q036,VALUE,1,Income,"$75,000 or greater",INC,INC75PLUS,2016

In [58]:
#Records by gender pie chart
gender = npa["Sex"].value_counts().reset_index()
gender.columns = ["Sex", "Count"]
fig12 = px.pie(
    gender,
    names="Sex",
    values="Count",
    title="Distribution of Records by Gender")
fig12.show()
#This doesn't seem very telling as the info results in 50/50 - missing data needs to be cleaned up

In [59]:
#Records by race/ethnicity pie cart
race_counts = npa["Race/Ethnicity"].value_counts().reset_index()
race_counts.columns = ["Race/Ethnicity", "Count"]
fig13 = px.pie(
    race_counts,
    names="Race/Ethnicity",
    values="Count",
    title="Distribution of Records by Race/Ethnicity")
fig13.show()
#This pie chart appears to tell more but all of the percentages are the same - missing data needs to be cleaned up.

In [ ]:
#Pie chart 
class_counts = npa["Class"].value_counts().reset_index()
class_counts.columns = ["Class", "Count"]
fig14 = px.pie(
    class_counts,
    names="Class",
    values="Count",
    title="Distribution by Health Classification")
fig14.show()
#Needs to be reviewed - data needs cleaned and what is this really telling the audience?

In [ ]:
#Averages by gender - Bar Chart

avg_sex = npa.groupby("Sex")["Data_Value"].mean().reset_index()
fig15 = px.bar(
    avg_sex,
    x="Sex",
    y="Data_Value",
    color="Sex",
    title="Average Data Value by Sex")
fig15.show()

In [61]:
#Averages by race/ethnicity - Bar Chart
avg_race = npa.groupby("Race/Ethnicity")["Data_Value"].mean().reset_index()
fig16 = px.bar(
    avg_race,
    x="Race/Ethnicity",
    y="Data_Value",
    color="Race/Ethnicity",
    title="Average Data Value by Race/Ethnicity")
fig16.show()

In [ ]:
#Averages by top 10 states - Bar Chart
state_avg = npa.groupby("LocationDesc")["Data_Value"].mean().reset_index()
top_states = state_avg.sort_values(by="Data_Value", ascending=False).head(10)
fig17 = px.bar(
    top_states,
    x="LocationDesc",
    y="Data_Value",
    color="LocationDesc",
    title="Top 10 States by Average Data Value")
fig17.show()

In [63]:
#Averages by Year and Gender - Bar Chart
year_sex = npa.groupby(["Year", "Sex"])["Data_Value"].mean().reset_index()
fig18 = px.bar(
    year_sex,
    x="Year",
    y="Data_Value",
    color="Sex",
    barmode="group",
    title="Average Data Value by Year and Gender")
fig18.show()

In [ ]:
#Scatterplot of data values and sample size
fig19 = px.scatter(
    npa,
    x="Sample_Size",
    y="Data_Value",
    color="Sex",
    hover_data=["LocationDesc", "Year"],
    title="Sample Size vs Data Value")
fig19.show()

In [ ]:
#Scatter Matrix of Data Value, Sample Size, & Confidence Limits
fig20 = px.scatter_matrix(
    npa,
    dimensions=["Data_Value", "Sample_Size", "Low_Confidence_Limit", "High_Confidence_Limit "],
    color="Sex",
    title="Scatter Matrix of Key Variables")
fig20.show()

In [ ]:
#Line Graph of Trend
trend = npa.groupby("Year")["Data_Value"].mean().reset_index()
fig21 = px.line(
    trend,
    x="Year",
    y="Data_Value",
    title="Average Data Value Over Time")
fig21.show()

In [68]:
#Distribution Box plot. Maybe can help show variability?
fig22 = px.box(
    npa,
    x="Sex",
    y="Data_Value",
    color="Sex",
    title="Distribution of Data Values by Sex")
fig22.show()