In [119]:
import plotly.express as px
import plotly as pl
import plotly.io as pio
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sb

In [120]:
npa = pd.read_csv('Nutrition__Physical_Activity__and_Obesity.csv')
npa.head()

C:\Users\djanke2\AppData\Local\Temp\ipykernel_20052\191502378.py:1: DtypeWarning:

Columns (0: Data_Value_Unit, 1: Total) have mixed types. Specify dtype option on import or set low_memory=False.

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$15,000 - $24,999",INC,INC1525
1,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$25,000 - $34,999",INC,INC2535
2,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$35,000 - $49,999",INC,INC3550
3,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$50,000 - $74,999",INC,INC5075
4,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$75,000 or greater",INC,INC75PLUS

In [121]:
row_count = len(npa)

print(row_count)

69300

In [122]:
#Filter out 5 Specific States
states = ["Mississippi", "West Virginia", "Colorado", "Ohio", "California"]

filtered_npa = npa[npa["LocationDesc"].str.contains("|".join(states), case=False, na=False)]
filtered_npa.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
112,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(37.638640123, -120.999999538)",OWS,OWS1,Q036,VALUE,6,Income,"$15,000 - $24,999",INC,INC1525
113,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(37.638640123, -120.999999538)",OWS,OWS1,Q036,VALUE,6,Income,"$25,000 - $34,999",INC,INC2535
114,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(37.638640123, -120.999999538)",OWS,OWS1,Q036,VALUE,6,Income,"$35,000 - $49,999",INC,INC3550
115,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(37.638640123, -120.999999538)",OWS,OWS1,Q036,VALUE,6,Income,"$50,000 - $74,999",INC,INC5075
116,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(37.638640123, -120.999999538)",OWS,OWS1,Q036,VALUE,6,Income,"$75,000 or greater",INC,INC75PLUS

In [123]:
#See how many rows are now in filtered data
row_count = len(filtered_npa)

print(row_count)

6300

In [124]:
#Make Overall Year and State columns
filtered_npa["Year"] = filtered_npa["YearStart"]
filtered_npa["State"] = filtered_npa["LocationDesc"]
filtered_npa.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1,Year,State
112,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS1,Q036,VALUE,6,Income,"$15,000 - $24,999",INC,INC1525,2016,California
113,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS1,Q036,VALUE,6,Income,"$25,000 - $34,999",INC,INC2535,2016,California
114,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS1,Q036,VALUE,6,Income,"$35,000 - $49,999",INC,INC3550,2016,California
115,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS1,Q036,VALUE,6,Income,"$50,000 - $74,999",INC,INC5075,2016,California
116,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS1,Q036,VALUE,6,Income,"$75,000 or greater",INC,INC75PLUS,2016,California

In [125]:
#Averages of 5 states - Bar Chart
state_avg = filtered_npa.groupby("LocationDesc")["Data_Value"].mean().reset_index()
#top_states = state_avg.sort_values(by="Data_Value", ascending=False).head()
fig1 = px.bar(
    top_states,
    x="LocationDesc",
    y="Data_Value",
    color="LocationDesc",
    title="Average of 5 States Data Value")
fig1.show()

In [126]:
fig2 = px.scatter(
    filtered_npa,
    x="Sample_Size",
    y="Data_Value",
    color="State",
    hover_data=["State", "Year"],
    title="Sample Size vs Data Value")
fig2.show()

In [127]:
fig3 = px.scatter(
    filtered_npa,
    x="Sample_Size",
    y="Data_Value",
    color="Sex",
    hover_data=["State", "Year"],
    title="Sample Size vs Data Value")
fig3.show()

In [128]:
fig4 = px.box(
    filtered_npa,
    x="Sex",
    y="Data_Value",
    color="Sex",
    title="Distribution of Data Values by Sex")
fig4.show()

In [129]:
#Look for obesity info
filtered_npa = filtered_npa[filtered_npa["Topic"].str.contains("Obesity", case=False, na=False)]

#Get the correct value types
filtered_npa["Data_Value"] = pd.to_numeric(filtered_npa["Data_Value"], errors="coerce")

#Plot information for specific info
plot_filtered_npa = filtered_npa.dropna(subset=["Age_yrs", "Data_Value", "LocationDesc"])

In [130]:
filtered_npa.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1,Year,State
112,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS1,Q036,VALUE,6,Income,"$15,000 - $24,999",INC,INC1525,2016,California
113,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS1,Q036,VALUE,6,Income,"$25,000 - $34,999",INC,INC2535,2016,California
114,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS1,Q036,VALUE,6,Income,"$35,000 - $49,999",INC,INC3550,2016,California
115,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS1,Q036,VALUE,6,Income,"$50,000 - $74,999",INC,INC5075,2016,California
116,2016,2016,CA,California,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,OWS1,Q036,VALUE,6,Income,"$75,000 or greater",INC,INC75PLUS,2016,California

In [131]:
plot_filtered_npa = (
    plot_filtered_npa
    .groupby(["State", "Age_yrs"])["Data_Value"]
    .mean()
    .reset_index()
)

In [138]:
import plotly.graph_objects as go

statesname = plot_filtered_npa["State"].unique()

fig5 = go.Figure()

# Add one trace per state
for state in states:
    state_filtered_npa = plot_filtered_npa[plot_filtered_npa["State"] == state]
    
    fig5.add_trace(
        go.Scatter(
            x=state_filtered_npa["Age_yrs"],
            y=state_filtered_npa["Data_Value"],
            mode="lines+markers",
            name=state,
            visible=(state == states[0])
            )
    )
fig5.show()

In [139]:
import plotly.graph_objects as go

statesname = plot_filtered_npa["State"].unique()

fig6 = go.Figure()

# Add one trace per state
for state in states:
    state_filtered_npa = plot_filtered_npa[plot_filtered_npa["State"] == state]
    
    fig6.add_trace(
        go.Scatter(
            x=state_filtered_npa["Age_yrs"],
            y=state_filtered_npa["Data_Value"],
            mode="lines+markers",
            name=state,
            visible=(state == states[0])
            )
    )

# Create dropdown buttons
buttons = []

for i, state in enumerate(states):
    visibility = [False] * len(states)
    visibility[i] = True
    
    buttons.append(
        dict(
            label=state,
            method="update",
            args=[
                {"visible": visibility},
                {"title": "Obesity Rates by Age in {state}"}
            ]
        )
    )
# Add dropdown to layout
fig6.update_layout(
    title=f"Obesity Rates by Age in {states[0]}",
    xaxis_title="Age Group",
    yaxis_title="Obesity Rate (%)",
    updatemenus=[
        dict(
            active=0,
            buttons=buttons,
            x=1.15,
            y=1
        )
    ]
)

fig6.show()

In [140]:
import plotly.graph_objects as go

states = plot_filtered_npa["State"].unique()

fig7 = go.Figure()

# Add one trace per state
for state in states:
    state_npa = plot_filtered_npa[plot_filtered_npa["State"] == state]
    
    fig7.add_trace(
        go.Scatter(
            x=state_npa["Age_yrs"],
            y=state_npa["Data_Value"],
            mode="lines+markers",
            name=state,
            visible=(state == states[0])  
        )
    )

# Create dropdown buttons
buttons = []

for i, state in enumerate(states):
    visibility = [False] * len(states)
    visibility[i] = True
    
    buttons.append(
        dict(
            label=state,
            method="update",
            args=[
                {"visible": visibility},
                {"title": "Obesity Rates by Age in {state}"}
            ]
        )
    )
# Add dropdown to layout
fig7.update_layout(
    title="Obesity Rates by Age in {states[0]}",
    xaxis_title="Age Group",
    yaxis_title="Obesity Rate (%)",
    updatemenus=[
        dict(
            active=0,
            buttons=buttons,
            x=1.15,
            y=1
        )
    ]
)

fig7 = px.line(
    plot_filtered_npa,
    x="Age_yrs",
    y="Data_Value",
    color="State",
    title="State Obesity Rates by Age"
)

fig7.show()

In [135]:
#states = ["Mississippi", "West Virginia", "Colorado", "Ohio", "California"]

# Filter to selected states
filtered = npa[npa["LocationDesc"].isin(states)]

# Aggregate (average obesity rate per state)
state_avg = (
    filtered
    .groupby("LocationDesc")["Data_Value"]
    .mean()
    .reset_index()
)

In [141]:
fig8 = px.choropleth(
    state_avg,
    locations="LocationDesc",
    color="Data_Value",
      scope="usa",
      title="Obesity Rates by State",
)

fig8.show()

I must be pulling data from the wrong area since its not showing me the information on the map.